name: Backend CI - Build & Unit Tests

on:
  # push:
    # paths:
    #   - 'back/**'
    #   - '.github/workflows/backend-ci.yml'
    # branches: [ "main" ]
  pull_request:
    paths:
      - 'back/**'
      - '.github/workflows/backend-ci.yml'
    # branches: [ "main" ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore back/EGAR.Back.sln

    - name: Build backend solution
      run: dotnet build back/EGAR.Back.sln --no-restore --configuration Release

    - name: Tests
      run: dotnet test back/EGAR.UnitTests/EGAR.UnitTests.csproj --no-build --configuration Release --verbosity normal  --logger "trx;LogFileName=test_results.trx" 

    #- name: Publish Test Results
    #  uses: EnricoMi/publish-unit-test-result-action@v2
    #  if: (!cancelled())
    #  with:
    #    files: "back/EGAR.UnitTests/TestResults/test_results.trx"
    
    # - name: Upload test results
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: test-results
    #     path: back/EGAR.UnitTests/TestResults/**/*.trx
        
